[package]                                                                                       
name = "binproj"                                                                                
version = "0.1.0"                                                                               
edition = "2021"                                                                                
                                                                                                
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
                                                                                                
[dependencies]                                                                                  
yaml-rust = "0.3.0"
yottadb = "1.0.0"
xcb = "0.9.0"